import type { Metadata } from "next";
import "@/styles/globals.css";
import DashboardBottomNav from "@/components/DashboardBottomNav";
import DashboardSidebar from "@/components/DashboardSidebar";
import DashboardHeader from "@/components/DashboardHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <DashboardHeader />
      <div className="bg-primary-extra-light/10 tab:pb-0 tab:pt-0 tab:pl-[90px] laptopM:pl-[220px] flex w-full justify-center pt-[50px] pb-[50px]">
        <div className="tab:px-[50px] h-full w-full px-3">{children}</div>
      </div>
      <DashboardSidebar />
      <DashboardBottomNav />
    </div>
  );
}
